apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: student-259252
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          
          image: niktt332/backend
          
          env:
            - name: MONGODB_RW_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mongodb-host-rw
            - name: MONGODB_RO_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mongodb-host-ro
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongodb-password

          ports:
          - containerPort: 5000
            name: backend-port

          startupProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 15
            failureThreshold: 2
            periodSeconds: 5  

          readinessProbe:
            httpGet:
              path: /up
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

            
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: student-259252
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: backend-port
